// Per-stack rendering: template variables, generated files from lcl.yml `files`, compose env + override, URLs.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import type { Catalog } from './catalog.js';
import { primaryPortName } from './config.js';
import { interpolate, renderTemplate, type Vars } from './config.js';
import type { PortMap, Paths, State } from './instance.js';

export const envName = (port: string) => `LCL_PORT_${port.toUpperCase().replace(/[^A-Z0-9]+/g, '_')}`;

/** Everything a `${…}` may refer to, for one stack (and optionally one service). */
export function variables(catalog: Catalog, state: Pick<State, 'id' | 'project' | 'ports'>, paths: Pick<Paths, 'dir'>, service?: string): Vars {
    const v: Vars = {
        stack: state.id,
        'stack.dir': paths.dir,
        root: catalog.root,
        project: state.project,
        offset: String(state.ports.offset),
        'compose.file': catalog.config.compose?.files[0] ?? '',
    };
    for (const [name, port] of Object.entries(state.ports.services)) v[`port.${name}`] = String(port);
    for (const [key, port] of Object.entries(state.ports.infra)) v[`port.${key}`] = String(port);
    if (service) {
        const definition = catalog.config.services[service];
        const portName = definition ? primaryPortName(definition) : undefined;
        v.service = service;
        v.port = portName ? String(state.ports.services[`${service}.${portName}`]) : '';
    }
    return v;
}

/** Every service (processes and containers) with its port for this stack — what `{{#each services}}` iterates. */
export function serviceList(catalog: Catalog, ports: PortMap): Array<{ name: string; port: number }> {
    return catalog.services.flatMap((service) => {
        const name = primaryPortName(service.def);
        return name ? [{ name: service.name, port: ports.services[`${service.name}.${name}`] }] : [];
    });
}

export function renderFiles(catalog: Catalog, vars: Vars, ports: PortMap): string[] {
    const list = serviceList(catalog, ports);
    const written: string[] = [];
    for (const f of catalog.config.files) {
        const template = readFileSync(join(catalog.root, f.template), 'utf8');
        const path = interpolate(f.path, vars, `files.path`);
        writeFile(path, renderTemplate(template, vars, list, f.template));
        written.push(path);
    }
    return written;
}

export function renderComposeEnv(catalog: Catalog, ports: PortMap, vars: Vars): string {
    const lines: string[] = ['# generated by lcl — do not edit'];
    for (const i of catalog.infra) lines.push(`${i.envVar}=${ports.infra[i.key]}`);
    for (const [name, port] of Object.entries(ports.services)) lines.push(`${envName(name)}=${port}`);
    for (const service of serviceList(catalog, ports)) lines.push(`${envName(service.name)}=${service.port}`);
    for (const [k, v] of Object.entries(catalog.config.compose?.environment ?? {})) lines.push(`${k}=${interpolate(v, vars, `compose.environment.${k}`)}`);
    return lines.join('\n') + '\n';
}

/** Compose override: every published port of every compose service, shifted; `!override` replaces the base list. */
export function renderComposeOverride(catalog: Catalog, ports: PortMap): string {
    const lines = ['# generated by lcl — do not edit', 'services:'];
    for (const compose of catalog.composeServices) {
        const mine = catalog.infra.filter((i) => i.compose === compose);
        if (mine.length === 0) continue;
        lines.push(`  ${compose}:`, '    ports: !override');
        for (const i of mine) lines.push(`      - "${ports.infra[i.key]}:${i.containerPort}"`);
    }
    return lines.join('\n') + '\n';
}

export function writeFile(path: string, content: string): void {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
}

export function urlsFor(catalog: Catalog, vars: Vars): Array<[string, string]> {
    return catalog.config.urls.map((u) => [u.label, interpolate(u.url, vars, `urls.${u.label}`)]);
}
